spring:
  application:
    name: payment-service
  config:
    import: "optional:file:.env[.properties]"
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5449/app}
    username: ${DB_USER:app}
    password: ${DB_PASS:app}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.default_schema: payments
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: payments
    create-schemas: true
    baseline-on-migrate: true

management:
  endpoints:
    web.exposure.include: health,info
  endpoint.health.probes.enabled: true

server:
  port: ${PORT:8083}
